### ISSUE TITLE
[Request] Can you do something with the PNG info tab as well?

### ISSUE THREAD

**Issue by enternalsaga** [bluelovers/sd-webui-pnginfo-beautify#1]
Forgive me if is not the right place to raise request for another extension...

**Comment by bluelovers** [comment]
already has this, so i don't know what u mean?

![image](https://github.com/bluelovers/sd-webui-pnginfo-beautify/assets/167966/db06a1e8-3ece-4af0-adb1-d31aab241ea6)

**Comment by enternalsaga** [comment]
in my A1111, the extension is only work in txt2img and img2img 
![image](https://github.com/bluelovers/sd-webui-pnginfo-beautify/assets/31148570/bc7be44c-fb6f-49e6-8469-1ca933bd2482)
the pnginfo got no affect
![image](https://github.com/bluelovers/sd-webui-pnginfo-beautify/assets/31148570/f3755396-cdea-4871-8e1b-54c31a9ffe66)
is it supposed to fuction normally with Png info tab ?

**Comment by bluelovers** [comment]
can u try force re-install this extension?
old install has a bug make it can't update to new version

**Comment by FredrikAir** [comment]
I have the same issue, the PNG Info tab is only original.
It works in txt2img.
I installed the extension today, and tried installing it manually also.

**Comment by bluelovers** [comment]
what version of webui u use?

and try press `F12` see `console log` does any error

**Comment by FredrikAir** [comment]
> what version of webui u use?
> 
> and try press `F12` see `console log` does any error

I use version 1.9.3

This error is in console:
![image](https://github.com/bluelovers/sd-webui-pnginfo-beautify/assets/82309730/f6171e62-3d75-4826-9c24-77dc1e46a7d4)
_3index.mts:70  sd-webui-pnginfo-beautify TypeError: Cannot read properties of null (reading 'parentNode')
    at renderInfo (render.ts:23:19)
    at index.mts:49:9_

**Comment by bluelovers** [comment]
> > what version of webui u use?
> > and try press `F12` see `console log` does any error
> 
> I use version 1.9.3
> 
> This error is in console: ![image](https://private-user-images.githubusercontent.com/82309730/334529317-f6171e62-3d75-4826-9c24-77dc1e46a7d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MzY4NzAsIm5iZiI6MTcxNjkzNjU3MCwicGF0aCI6Ii84MjMwOTczMC8zMzQ1MjkzMTctZjYxNzFlNjItM2Q3NS00ODI2LTljMjQtNzdkYzFlNDZhN2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDIyNDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ODQ2ZDFlYTU2YzRlMzY3YTY5MDBhZGE3ZTc5OGIyYWE3NzZlZDVmNmIxZjM0MzU5MzM1MjlhMzJmMzRhNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.luos4hV71K0aUjWpbYHuuJ5x3jJvsvYluHiuRqDY4VI) _3index.mts:70 sd-webui-pnginfo-beautify TypeError: Cannot read properties of null (reading 'parentNode') at renderInfo (render.ts:23:19) at index.mts:49:9_

ok, i know why now.

it because i also support some other extension
but when it didn't install, will show this bug

**Comment by bluelovers** [comment]
i also add a hard core css selector for sd webui 1.9.3 didn't has class name for pnginfo now

**Comment by FredrikAir** [comment]
> i also add a hard core css selector for sd webui 1.9.3 didn't has class name for pnginfo now

Great, it works.
Thanks :)

I like the links to Civitai also, so much easier.

![image](https://github.com/bluelovers/sd-webui-pnginfo-beautify/assets/82309730/7aaaf9d2-7138-42d3-bf9e-ec913e16627d)

**Comment by ischia-exigenter** [comment]
This extension stopped working for me today, I'm not sure why, but I'm always changing something or testing some new extensions, so it's impossible to know. I have tried stopping, deleting, reinstalling, restarting; but no luck, I've only been using the extension one month, and until recently it worked good. Thanks

Here's the exception in a Firefox browser:

```
sd-webui-pnginfo-beautify TypeError: 
    extractPromptAndInfoFromRaw parser.ts:138
    parseFromRawInfoGenerator index.ts:62
    parseFromRawInfo index.ts:51
    renderInfo render.ts:71
    observer index.mts:38
    MutationCallback* index.mts:23
    executeCallbacks file=script.js:83
    mutationObserver file=script.js:109
    MutationCallback* file=script.js:106
    EventListener.handleEvent* file=script.js:105
[index.mts:39:23](http://localhost:7860/file=extensions/src/index.mts)
    observer index.mts:39
    (Async: promise callback)
    observer index.mts:39
    (Async: MutationCallback)
    <anonymous> index.mts:23
    executeCallbacks file=script.js:83
    mutationObserver file=script.js:109
    (Async: MutationCallback)
    <anonymous> file=script.js:106
    (Async: EventListener.handleEvent)
    <anonymous> file=script.js:105
```

**Comment by bluelovers** [comment]
can u upload raw pnginfo txt or a ai image with pnginfo?

![image](https://github.com/bluelovers/sd-webui-pnginfo-beautify/assets/167966/6dd5990d-c7b6-4704-b6a4-f29bfe69478a)
