### ISSUE TITLE
Extras Tab Upscaler

### ISSUE THREAD

**Issue by BangDroid** [bluelovers/sd-webui-pnginfo-beautify#2]
Not exactly an issue but a question.

I am trying to find a way to save the "Upscaler 2 visibility" value inside output images. Currently the only data that saves is e.g.
```
Postprocess upscale by: 4, Postprocess upscaler: R-ESRGAN 4x+ Anime6B, Postprocess upscaler 2: SwinIR_4x
```
But without the visibility value, it's very hard to review images for settings.

Would **sd-webui-pnginfo-beautify** help with this, or would you know if this is possible? I asked ChatGPT but it's doesn't know what it's talking about.

**Comment by bluelovers** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/16427
