### ISSUE TITLE
 extension-style-vars extension: sv_negative section markup error

### ISSUE THREAD

**Issue by therifler** [bluelovers/sd-webui-pnginfo-beautify#3]
sv_negative section has broken markup. sv_prompt section has valid markup with colors.

**Comment by bluelovers** [comment]
i need the pnginfo for test

**Comment by bluelovers** [comment]
also if u are just mean `sv_negative` didn't markup, that is because i didn't set it for markup

can see here for see what field will markup

https://github.com/bluelovers/sd-webui-pnginfo-beautify/blob/dev/src/row-config.ts

**Comment by therifler** [comment]
I thought it was a mistake. In that case, that's it.

**Comment by bluelovers** [comment]
> I thought it was a mistake. In that case, that's it.

do u need `sv_negative` markup?

**Comment by therifler** [comment]
I think it's good to make it all consistent and look good. It would be nice to have that markup, that's where I give weights, etc.

**Comment by bluelovers** [comment]
ok
